name: rate_watcher
description: "Rate Watcher, Your gateway to global insights."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  google_fonts: ^6.2.1
  country_flags: ^2.2.0
  provider: ^6.1.2
  go_router: ^14.1.4
  font_awesome_flutter: ^10.7.0
  connectivity_plus: ^6.0.3
  flutter_launcher_icons: ^0.13.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/exchange.png"

flutter:
  uses-material-design: true
  assets:
     - assets/


